In [6]:
import pandas as pd
import numpy as np

In [7]:
sales = pd.read_csv("../data/sales_daily.csv")
sku = pd.read_csv("../data/sku_master.csv")
calendar = pd.read_csv("../data/calendar.csv")
inventory = pd.read_csv("../data/inventory_snapshots.csv")

In [3]:
print("Sales:", sales.shape)
print("SKU:", sku.shape)
print("Calendar:", calendar.shape)
print("Inventory:", inventory.shape)

Sales: (129517, 6)
SKU: (200, 6)
Calendar: (731, 6)
Inventory: (18533, 6)

In [8]:
sales.head()

         date   sku_id  units_sold    revenue  unit_price  promo_flag
0  2024-12-07  SKU0011          10   18164.90     1816.49           0
1  2024-10-19  SKU0031          14   34807.36     2486.24           0
2  2025-07-22  SKU0141           8   14235.76     1779.47           0
3  2024-10-11  SKU0197          17  108121.02     6360.06           0
4  2024-07-18  SKU0097           2   13492.72     6746.36           0

In [9]:
sku.head()

    sku_id   category subcategory launch_date  unit_cost  list_price
0  SKU0001      Decor    Wall Art  2024-01-01    3151.81     6105.58
1  SKU0002      Decor     Candles  2024-01-01    3484.78     6763.97
2  SKU0003   Textiles      Throws  2024-01-01    2929.70     6576.29
3  SKU0004  Furniture    Shelving  2024-01-01    1321.33     2473.90
4  SKU0005      Decor    Wall Art  2024-01-01    1689.46     2436.20

In [10]:
calendar.head()

         date  week  month  season  is_holiday promo_event
0  2024-01-01     1      1  Winter           1         NaN
1  2024-01-02     1      1  Winter           0         NaN
2  2024-01-03     1      1  Winter           0         NaN
3  2024-01-04     1      1  Winter           0         NaN
4  2024-01-05     1      1  Winter           0         NaN

In [11]:
inventory.head()

,date,sku_id,on_hand_units,on_order_units,lead_time_days,reorder_point
0,2024-01-01,SKU0001,168,242,14.0,132
1,2024-01-08,SKU0001,156,144,14.0,132
2,2024-01-15,SKU0001,201,256,14.0,132
3,2024-01-22,SKU0001,143,0,14.0,132
4,2024-01-29,SKU0001,157,107,14.0,132

In [12]:
print("SALES COLUMNS")
print(sales.columns.tolist())

print("\nSKU COLUMNS")
print(sku.columns.tolist())

print("\nCALENDAR COLUMNS")
print(calendar.columns.tolist())

print("\nINVENTORY COLUMNS")
print(inventory.columns.tolist())

SALES COLUMNS
['date', 'sku_id', 'units_sold', 'revenue', 'unit_price', 'promo_flag']

SKU COLUMNS
['sku_id', 'category', 'subcategory', 'launch_date', 'unit_cost', 'list_price']

CALENDAR COLUMNS
['date', 'week', 'month', 'season', 'is_holiday', 'promo_event']

INVENTORY COLUMNS
['date', 'sku_id', 'on_hand_units', 'on_order_units', 'lead_time_days', 'reorder_point']

In [13]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 129517 entries, 0 to 129516
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        129517 non-null  str
 1   sku_id      129517 non-null  str
 2   units_sold  129517 non-null  int64
 3   revenue     128222 non-null  float64
 4   unit_price  128201 non-null  float64
 5   promo_flag  129517 non-null  int64
dtypes: float64(2), int64(2), str(2)
memory usage: 5.9 MB

In [14]:
sku.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku_id       200 non-null    str
 1   category     200 non-null    str
 2   subcategory  200 non-null    str
 3   launch_date  200 non-null    str
 4   unit_cost    200 non-null    float64
 5   list_price   200 non-null    float64
dtypes: float64(2), str(4)
memory usage: 9.5 KB

In [15]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         731 non-null    str
 1   week         731 non-null    int64
 2   month        731 non-null    int64
 3   season       731 non-null    str
 4   is_holiday   731 non-null    int64
 5   promo_event  84 non-null     str
dtypes: int64(3), str(3)
memory usage: 34.4 KB

In [16]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 18533 entries, 0 to 18532
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            18533 non-null  str
 1   sku_id          18533 non-null  str
 2   on_hand_units   18533 non-null  int64
 3   on_order_units  18533 non-null  int64
 4   lead_time_days  18336 non-null  float64
 5   reorder_point   18533 non-null  int64
dtypes: float64(1), int64(3), str(2)
memory usage: 868.9 KB

In [17]:
print("SALES MISSING VALUES")
print(sales.isnull().sum())

SALES MISSING VALUES
date             0
sku_id           0
units_sold       0
revenue       1295
unit_price    1316
promo_flag       0
dtype: int64

In [18]:
print("SKU MISSING VALUES")
print(sku.isnull().sum())

SKU MISSING VALUES
sku_id         0
category       0
subcategory    0
launch_date    0
unit_cost      0
list_price     0
dtype: int64

In [19]:
print("CALENDAR MISSING VALUES")
print(calendar.isnull().sum())

CALENDAR MISSING VALUES
date             0
week             0
month            0
season           0
is_holiday       0
promo_event    647
dtype: int64

In [20]:
print("INVENTORY MISSING VALUES")
print(inventory.isnull().sum())

INVENTORY MISSING VALUES
date                0
sku_id              0
on_hand_units       0
on_order_units      0
lead_time_days    197
reorder_point       0
dtype: int64

In [21]:
sales.duplicated().sum()

np.int64(387)

In [22]:
sku.duplicated().sum()

np.int64(0)

In [23]:
calendar.duplicated().sum()

np.int64(0)

In [24]:
inventory.duplicated().sum()

np.int64(0)

In [25]:
sales[sales["units_sold"] < 0] #inserted negative sales quantities

              date   sku_id  units_sold    revenue  unit_price  promo_flag
55      2025-11-11  SKU0061          -1   31379.44     3922.43           0
2612    2025-03-23  SKU0181          -1   41753.36      614.02           0
3620    2025-10-29  SKU0053          -1   55884.17     3492.76           1
4105    2025-02-11  SKU0014          -1   20509.12     2563.64           0
6817    2024-03-12  SKU0117          -1   61064.15     1744.69           0
...            ...      ...         ...        ...         ...         ...
126107  2025-12-26  SKU0170          -1    9616.10      874.19           1
126316  2025-04-08  SKU0099          -1  188603.68     8200.16           0
126899  2025-11-15  SKU0013          -1   43844.80     4384.48           0
127571  2024-06-07  SKU0069          -1   82802.99     2300.08           1
128851  2024-11-07  SKU0151          -1   38814.72     1617.28           0

[132 rows x 6 columns]

In [26]:
sales.describe()

          units_sold        revenue     unit_price     promo_flag
count  129517.000000  128222.000000  128201.000000  129517.000000
mean       15.965711   61741.726637    3885.059591       0.118618
std        11.876234   60143.981137    2086.898599       0.323339
min        -1.000000       0.000000     402.810000       0.000000
25%         7.000000   19197.120000    2111.910000       0.000000
50%        13.000000   42456.400000    3642.530000       0.000000
75%        22.000000   84146.940000    5570.020000       0.000000
max       105.000000  519386.980000    8957.690000       1.000000